### ISSUE TITLE
Panzer Dragoon Saga - Not work anymore with the last core update

### ISSUE THREAD

**Issue by jiraz01** [FCare/Kronos#1438]
You only hear the music and you can see the background, you no longer see the characters or any game action.

(PAL version, any change in core options are useless)

**Comment by BenjaminSiskoo** [comment]
Thanks for the report

**Comment by moebiusJean** [comment]
I have the same problem with the standalone emulator also. Actually the game starts normally but after finishing the first open area and entering the tunnel, music and buttons still work but the screen gets black and nothing is visible in 2.5.0, just before Canyon Deep Gulch area.

**Comment by fafling** [comment]
Hello can you provide a save state from just before the problem happens ?

**Comment by moebiusJean** [comment]
Here is the save file before the tunnel, when you enter the tunnel and exit at the other side, the screen gets black. This is for the panzer dragoon saga PAL version.
[kronos250panzerPalCrashSave.zip](https://github.com/FCare/Kronos/files/10708013/kronos250panzerPalCrashSave.zip)

**Comment by fafling** [comment]
I reproduce the same issue as @jiraz01 in public v2.5.0, with the 3 regions, not just PAL : the sprites are missing in game.

The command list is visible in VDP1 debug screen.

The issue appears in the February 5th WIP (d936f33 in fbaccess branch). The preceding February 3rd WIP (b0ab4b7) doesn't have it.

It can be reproduced rapidly by loading this save file made at the 1st save point :
[bkram_panzer_dragoon_saga.zip](https://github.com/FCare/Kronos/files/10712095/bkram_panzer_dragoon_saga.zip)

**Comment by fafling** [comment]
A workaround is to start the game with the emulated bios, as reported by user Turtle on Discord (check "Enable bios emulation" in the General panel of Kronos settings).

**Comment by legaiaflame** [comment]
Enabling HLE Bios in the RetroArch Kronos core options did not work for me. Here is what the current issue looks like specifically:

https://pdsoasis.github.io/panzerra1.png

https://pdsoasis.github.io/panzerra2.png

**Comment by legaiaflame** [comment]
Is it possible to revert to a previous update where the game was running correctly? The update where the invisible text was fixed, I believe was the last confirmed working build. This update I believe:

https://github.com/FCare/Kronos/issues/1161

**Comment by legaiaflame** [comment]
Also, on a side note: I tested some other Saturn games on the current RetroArch Kronos build. And with some games the sound/framerate is speed up way too fast. For instance, with Nights into Dreams.

**Comment by fafling** [comment]
Fixed in current WIP.

**Comment by legaiaflame** [comment]
Do you mean it's fixed in the latest update? I just tried the Kronos core in RetroArch (updated it). And I still get a black screen in the starting area...

**Comment by fafling** [comment]
The retroarch Kronos core v2.5.0 fec6e18 corresponds to the public standalone Kronos v2.5.0.
This problem isn't fixed in those.

**Comment by fafling** [comment]
@BenjaminSiskoo This is fixed in public v2.6.1.
